# Git deployment configuration for PowerShell with deployment fixes
# If you encounter build issues with merge conflicts:
# The fix-deployment.js script will automatically force-replace problematic files

[environment]
type = "node"
DOCKER = "true"

[phases.setup]
nixPkgs = ["nodejs", "git"]

[phases.install]
cmds = ["npm install"]

[phases.prebuild]
cmds = ["node scripts/fix-deployment.js"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
