# Git deployment configuration for PowerShell
# If you encounter detached HEAD state or worktree issues:
# git worktree list  # Check current worktrees
# git checkout main  # Try to switch to main branch
# git add .          # Add all changes
# git commit -m "Your commit message"
# git push --set-upstream origin new-main-branch  # For new branches
# git push origin main  # For existing branches

[environment]
type = "node"

[phases.install]
cmds = ["npm install"]

[phases.build]
# Include this phase only if your backend requires a build step (e.g., transpilation)
# cmds = ["npm run build"]

[start]
cmd = "npm start"
